In [2]:
import pandas as pd
df1 = pd.read_csv("archive/student-scores.csv")
df = df1.copy()
df.head()

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76

In [3]:
! pip install SMOTE

Requirement already satisfied: SMOTE in c:\users\neeraj sona\anaconda3\lib\site-packages (0.1)
Requirement already satisfied: numpy>=1.14.3 in c:\users\neeraj sona\anaconda3\lib\site-packages (from SMOTE) (1.24.3)
Requirement already satisfied: scikit-learn>=0.19.1 in c:\users\neeraj sona\anaconda3\lib\site-packages (from SMOTE) (1.3.0)
Requirement already satisfied: scipy>=1.5.0 in c:\users\neeraj sona\anaconda3\lib\site-packages (from scikit-learn>=0.19.1->SMOTE) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\neeraj sona\anaconda3\lib\site-packages (from scikit-learn>=0.19.1->SMOTE) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\neeraj sona\anaconda3\lib\site-packages (from scikit-learn>=0.19.1->SMOTE) (2.2.0)

In [4]:
df.columns
df.drop(columns=['id','first-name','last_name','email'], axis=1, inplace=True)

KeyError: "['first-name'] not found in axis"

In [ ]:
df['total_score'] =  df['math_score'] + df['history_score'] + df['physics_score'] + df['chemistry_score'] + df['biology_score'] + df['english_score'] + df['geography_score']
df['average_score'] = df["total_score"] / 7
df.head()

In [ ]:
len(df['career_aspiration'].unique())

In [ ]:
gender_map = {'male': 0, 'female': 1}
part_time_job_map = {False: 0, True: 1}
extracurricular_activities_map = {False: 0, True: 1}
career_aspiration_map = {
        'Lawyer': 0, 'Doctor': 1, 'Government Officer': 2, 'Artist': 3, 'Unknown': 4,
        'Software Engineer': 5, 'Teacher': 6, 'Business Owner': 7, 'Scientist': 8,
        'Banker': 9, 'Writer': 10, 'Accountant': 11, 'Designer': 12,
        'Construction Engineer': 13, 'Game Developer': 14, 'Stock Investor': 15,
        'Real Estate Developer': 16
    }
# Apply mapping to the DataFrame
df['gender'] = df['gender'].map(gender_map)
df['part_time_job'] = df['part_time_job'].map(part_time_job_map)
df['extracurricular_activities'] = df['extracurricular_activities'].map(extracurricular_activities_map)
df['career_aspiration'] = df['career_aspiration'].map(career_aspiration_map)

In [ ]:
df.head()